---
- name: Install nginx
  apt: pkg=nginx state=present update_cache=true

- name: Copy nginx site config
  template: src=themmc dest=/etc/nginx/sites-available
- name: Add symlink to sites-enabled
  file: state=link src=/etc/nginx/sites-available/themmc dest=/etc/nginx/sites-enabled/themmc
  notify: reload nginx
