---
- name: Backup Wordpress
  hosts: oldmmc
  user: root
  tasks:
    - name: Backup wordpressdb
      mysql_db: name={{wp_db_name}} state=dump target=/root/{{wp_db_name}}-{{ansible_date_time.epoch}}.sql

