---
- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: themmc
  user: root
  # remote_user: user
  # sudo: yes

  roles:
    - mysql 
    - nginx
    - php-fpm
    - wordpress
    - postfix
